version: "3.1"

services:
  mariadb:
    image: mariadb:10.3
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=zkdb
    expose:
      - "3306"
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mariadb
    restart: always
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: root 
    ports:
      - 8889:80
    links:
      - mariadb
    
  nginx:
    image: richarvey/nginx-php-fpm:1.7.3
    container_name: nginx
    restart: always
    environment: 
        - PUID=1000
    ports: 
      - 8888:80
    volumes:
      - ./conf.d:/etc/nginx/sites-available
      - ./public:/var/www/public